// ASProxy AJAX Wrapper Core
// Last update: 2010-01-23 coded by Salar.Kh //
Object.extend=function(a,b,d){for(var e in b)d==false&&a[e]!=null||(a[e]=b[e]);return a};function _ArrayAdd(a,b,d){a[b]=d}_ASProxyXMLHttpRequest=typeof XMLHttpRequest!="undefined"?XMLHttpRequest:null;_AJAXInternal=function(){try{return new _ASProxyXMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(b){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(d){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(e){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}};
XMLHttpRequest=function(){};Object.extend(XMLHttpRequest.prototype,{_ajax:new _AJAXInternal},true);
Object.extend(XMLHttpRequest.prototype,{_headers:[],_async:false,_reqUrl:"",_caller:null,_refresh:function(){_caller=this;this._attachAllEvent()},_attachAllEvent:function(){try{this._ajax.onreadystatechange=this._readystatechange}catch(a){}try{this._ajax.onload=this._load}catch(b){}try{if(this.onerror!=null)this._ajax.onerror=this._error}catch(d){}try{if(this.onprogress!=null)this._ajax.onprogress=this._progress}catch(e){}try{if(this.onabort!=null)this._ajax.onabort=this._abort}catch(c){}try{if(this.ontimeout!=
null)this._ajax.ontimeout=this._timeout}catch(f){}try{if(this.onuploadprogress!=null)this._ajax.onuploadprogress=this._uploadprogress}catch(g){}try{if(this.onloadstart!=null)this._ajax.onloadstart=this._loadstart}catch(h){}},_updateProperties:function(){try{this.responseText=this._ajax.responseText}catch(a){}try{this.responseXML=this._ajax.responseXML}catch(b){}try{this.status=this._ajax.status}catch(d){}try{this.statusText=this._ajax.statusText}catch(e){}try{this.readyState=this._ajax.readyState}catch(c){}try{this.responseBody=
this._ajax.responseBody}catch(f){}try{this.multipart=this._ajax.multipart}catch(g){}},_readystatechange:function(a){if(_caller!=null&&typeof _caller._updateProperties!="undefined"){_caller._updateProperties();_caller.onreadystatechange!=null&&_caller.onreadystatechange(a)}},_load:function(a){if(_caller!=null&&typeof _caller._updateProperties!="undefined"){_caller._updateProperties();_caller.onload!=null&&_caller.onload(a)}},_error:function(a){if(_caller!=null&&typeof _caller._updateProperties!="undefined"){_caller._updateProperties();
_caller.onerror!=null&&_caller.onerror(a)}},_progress:function(a){if(_caller!=null&&typeof _caller._updateProperties!="undefined"){_caller._updateProperties();_caller.onprogress!=null&&_caller.onprogress(a)}},_abort:function(a){if(_caller!=null&&typeof _caller._updateProperties!="undefined"){_caller._updateProperties();_caller.onabort!=null&&_caller.onabort(a)}},_timeout:function(a){if(_caller!=null&&typeof _caller._updateProperties!="undefined"){_caller._updateProperties();_caller.ontimeout!=null&&
_caller.ontimeout(a)}},_uploadprogress:function(a){if(_caller!=null&&typeof _caller._updateProperties!="undefined"){_caller._updateProperties();_caller.onuploadprogress!=null&&_caller.onuploadprogress(a)}},_loadstart:function(a){if(_caller!=null&&typeof _caller._updateProperties!="undefined"){_caller._updateProperties();_caller.onloadstart!=null&&_caller.onloadstart(a)}},UNSENT:0,OPENED:1,HEADERS_RECEIVED:2,LOADING:3,DONE:4,SECURITY_ERR:18,NETWORK_ERR:19,ABORT_ERR:20,abort:function(){this._refresh();
this._ajax.abort();this._updateProperties()},getAllResponseHeaders:function(){this._refresh();this._updateProperties();return this._ajax.getAllResponseHeaders()},getResponseHeader:function(a){this._refresh();this._updateProperties();return this._ajax.getResponseHeader(a)},open:function(a,b,d,e,c){if(arguments.length<3)d=true;this._reqUrl=b;b=this._EncodeAJAXUrl(a,b,e,c);a=this._ASProxyEncodeAJAXMethod(a);this._async=d;this._refresh();this._ajax.open(a,b,d,e,c);this._updateProperties()},send:function(a){this._ajax.setRequestHeader("X-ASProxy-AJAX-Headers",
this._EncodeArray(this._headers));this._ajax.setRequestHeader("X-ASProxy-AJAX-Referrer",_reqInfo.pageUrl);if(a&&a.nodeType){a=window.XMLSerializer?(new window.XMLSerializer).serializeToString(a):a.xml;this._headers["Content-Type"]||this._ajax.setRequestHeader("Content-Type","application/xml")}this._refresh();this._ajax.send(a);this._updateProperties()},sendAsBinary:function(a){this._ajax.setRequestHeader("X-ASProxy-AJAX-Headers",this._EncodeArray(this._headers));this._ajax.setRequestHeader("X-ASProxy-AJAX-Referrer",
_reqInfo.pageUrl);this._refresh();this._ajax.sendAsBinary(a);this._updateProperties()},setRequestHeader:function(a,b){_ArrayAdd(this._headers,a,b);this._refresh();this._ajax.setRequestHeader(a,b);this._updateProperties()},overrideMimeType:function(a){this._refresh();this._ajax.overrideMimeType(a);this._updateProperties()},toString:function(){return"[XMLHttpRequest]"},readyState:0,responseText:"",responseXML:null,responseBody:0,status:0,statusText:"",channel:null,multipart:false,onreadystatechange:null,
onload:null,onerror:null,onprogress:null,onabort:null,ontimeout:null,onuploadprogress:null,onloadstart:null},true);
Object.extend(XMLHttpRequest.prototype,{_ASProxyEncodeAJAXMethod:function(a){if(a==null)return a;return a.toLowerCase()=="post"?"POST":"GET"},_EncodeArray:function(a){var b="{";for(var d in a){var e=a[d];if(e!=null&&typeof e!="function")b+='"'+d+'"|#|"'+e+'"|^|'}b+="}";return b},_ASProxyEncoderAJAXUrl:function(a,b,d,e){b=b;var c;if(_ASProxy.IsClientSideUrl(b)||_ASProxy.IsSelfBookmarkUrl(b))return b;if(_ASProxy.IsEncodedByASProxy(b)){c=_ASProxy.GetUrlParamValue("ajaxurl",b)+"";if(c=="")c=_ASProxy.GetUrlParamValue("url",
b)+"";if(c!="")b=c=_Base64_decode(_ASProxy.B64UnknownerRemove(c))}b=_ASProxy.CorrectLocalUrlToOrginal(b);if(_ASProxy.IsVirtualUrl(b))b=_ASProxy.JoinUrls(b,_reqInfo.pagePath,_reqInfo.rootUrl);c=_ASProxy.Pages.pgAjax;c+="?dec="+(_userConfig.EncodeUrl+0)+"&ajaxurl=";c=c;c+=_userConfig.EncodeUrl?_ASProxy.B64UnknownerAdd(_Base64_encode(b)):b;c+="&method="+a;if(d!=null)c+="&use="+_ASProxy.B64UnknownerAdd(_Base64_encode(d));if(e!=null)c+="&pas="+_ASProxy.B64UnknownerAdd(_Base64_encode(e));return c},_EncodeAJAXUrl:function(a,
b,d,e){return this._ASProxyEncoderAJAXUrl(a,b,d,e)}},true);if(_ASProxyXMLHttpRequest&&_ASProxyXMLHttpRequest.wrapped)XMLHttpRequest.wrapped=_ASProxyXMLHttpRequest.wrapped;