// ASProxy Dynamic Encoder
// ASProxy encoder for dynamically created objects //
// Last update: 2009-11-17 coded by Salar Khalilzadeh //
_ASProxy={Debug_UseAbsoluteUrl:false,TraceCookies:false,LogEnabled:false,Activities:{},Pages:{pgGetAny:"getany.ashx",pgGetHtml:"gethtml.ashx",pgGetJS:"getjs.ashx",pgImages:"images.ashx",pgDownload:"download.ashx",pgAuthorization:"authorization.aspx"},ClientSideUrls:["mailto:","file://","javascript:","vbscript:","jscript:","vbs:","ymsgr:","data:"],NonVirtualUrls:["http://","https://","mailto:","ftp://","file://","telnet://","news://","nntp://","ldap://","ymsgr:","javascript:","vbscript:","jscript:",
"vbs:","data:"]};_ASProxy.EncodedUrls=[_reqInfo.ASProxyPageName+"?dec=",_ASProxy.Pages.pgGetHtml+"?dec=",_ASProxy.Pages.pgImages+"?dec=",_ASProxy.Pages.pgGetJS+"?dec=",_ASProxy.Pages.pgDownload+"?dec=",_ASProxy.Pages.pgAuthorization+"?dec=",_ASProxy.Pages.pgGetAny+"?dec="];document.OriginalWrite=document.write;document.OriginalWriteLn=document.writeln;window.OriginalOpen=window.open;window.LocationReplace=window.location.replace;window.LocationAssign=window.location.assign;window.LocationReload=window.location.reload;
ENC_Page=0;ENC_Images=1;ENC_Any=2;ENC_Frames=3;
function __UrlEncoder(a,b,c,f){if(_ASProxy.IsClientSideUrl(a)||_ASProxy.IsSelfBookmarkUrl(a))return a;if(c!=true)a=_ASProxy.CorrectLocalUrlToOrginal(a);if(_ASProxy.IsVirtualUrl(a))a=_ASProxy.JoinUrls(a,_reqInfo.pagePath,_reqInfo.rootUrl);c=b==ENC_Images?_ASProxy.Pages.pgImages:b==ENC_Any?_ASProxy.Pages.pgGetAny:b==ENC_Frames?_ASProxy.Pages.pgGetHtml:_reqInfo.ASProxyPageName;if(typeof _ASProxy.Debug_UseAbsoluteUrl!="undefined"&&_ASProxy.Debug_UseAbsoluteUrl)c=_reqInfo.ASProxyPath+c;c+="?dec="+(_userConfig.EncodeUrl+
0)+"&url=";b=_ASProxy.ReturnBookmarkPart(a);if(b!="")a=_ASProxy.RemoveBookmarkPart(a);c=c;c+=_userConfig.EncodeUrl?_ASProxy.B64UnknownerAdd(_Base64_encode(a)):a;if(f!=null)c+="&"+f;c+=b;return c}_ASProxy.JoinUrls=function(a,b,c){if(b.lastIndexOf("/")!=b.length-1)b+="/";if(c.lastIndexOf("/")!=c.length-1)c+="/";return a=a.indexOf("/",0)==0?c+"."+a:b+a};
_ASProxy.IsClientSideUrl=function(a){if(typeof a!="string")return false;a=a.toLowerCase();for(i=0;i<_ASProxy.ClientSideUrls.length;i++)if(_ASProxy.StrStartsWith(a,_ASProxy.ClientSideUrls[i]))return true;return false};_ASProxy.IsVirtualUrl=function(a){if(typeof a!="string")return true;a=a.toLowerCase();for(i=0;i<_ASProxy.NonVirtualUrls.length;i++)if(_ASProxy.StrStartsWith(a,_ASProxy.NonVirtualUrls[i]))return false;return true};
_ASProxy.IsSelfBookmarkUrl=function(a){if(typeof a!="string")return false;a=a.toLowerCase();if(_ASProxy.StrStartsWith(a,"#"))return true;var b=window.location.href.toLowerCase()+"#";if(a.indexOf(b,0)==0)return true;return false};_ASProxy.ReturnBookmarkPart=function(a){if(typeof a!="string")return"";var b=a.indexOf("#",0);if(b!=-1)return a=a.substring(b,a.length);else return""};
_ASProxy.RemoveBookmarkPart=function(a){if(typeof a!="string")return null;var b=a.indexOf("#",0);if(b!=-1)a=a.substring(0,b);return a};_ASProxy.CorrectLocalUrlToOrginalCheck=function(a){if(_ASProxy.IsClientSideUrl(a)||_ASProxy.IsSelfBookmarkUrl(a))return a;return _ASProxy.CorrectLocalUrlToOrginal(a)};
_ASProxy.CorrectLocalUrlToOrginal=function(a){if(typeof a!="string")return null;var b=a.toLowerCase(),c=_reqInfo.ASProxyRoot.toLowerCase(),f=_reqInfo.ASProxyPath.toLowerCase(),g=_reqInfo.ASProxyPageName.toLowerCase(),d=_reqInfo.pageUrlNoQuery,e=false,j=b.indexOf(g,0);g=g.length;if(j==-1){j=b.indexOf(f,0);g=f.length;d=_reqInfo.pagePath;e=true}if(j==-1){j=b.indexOf(c,0);g=c.length;d=_reqInfo.rootUrl;e=true}if(d.substr(d.length-1,1)=="/"){d=d.substr(0,d.length-1);e=true}if(j==0){a=a.substr(g,a.length);
b="/";if(a.substr(0,1)=="/")b="";if(e==false)b="";return d+b+a}else return a};_ASProxy.B64UnknownerAdd=function(a){if(typeof a!="string")return _reqInfo.UrlUnknowner;var b=_reqInfo.UrlUnknowner.toLowerCase(),c=a.toLowerCase();return(b=!_ASProxy.StrEndsWith(c,b))?a+_reqInfo.UrlUnknowner:a};_ASProxy.Log=function(){if(_ASProxy.LogEnabled&&typeof console!="undefined")try{console.debug("ASProxy log:");for(var a="",b=0;b<arguments.length;b++)a+=arguments[b]+"\n";console.debug(a)}catch(c){}};
_ASProxy.IsEncodedByASProxy=function(a){if(typeof a!="string")return false;a=a.toLowerCase();var b=_reqInfo.ASProxyPath.toLowerCase();for(i=0;i<_ASProxy.EncodedUrls.length;i++)if(_ASProxy.StrStartsWith(a,_ASProxy.EncodedUrls[i]))return true;else if(_ASProxy.StrStartsWith(a,b+_ASProxy.EncodedUrls[i]))return true;return false};
_ASProxy.GetBookmarkOnlyForCurrentPage=function(a){var b=document.location.href.toLowerCase(),c=a.toLowerCase(),f=a.indexOf("#",0);if(f!=-1){b=c.indexOf(b,0);return b==-1?a:_reqInfo.pageUrl+a.substring(f,a.length)}else return a};
_ASProxy.AttachEvent=function(a,b,c,f){try{if(a==null)return false;if(a.addEventListener){a.addEventListener(b,c,f);return true}else if(a.attachEvent){var g=a.attachEvent("on"+b,c);return g}else try{a["on"+b]=c}catch(d){_ASProxy.Log('AttachEvent"on"',d)}}catch(e){_ASProxy.Log("AttachEvent",e)}};_ASProxy.StrTrimLeft=function(a){return a.replace(/^\s*/,"")};_ASProxy.StrTrimRight=function(a){return a.replace(/\s*$/,"")};_ASProxy.StrTrim=function(a){return a.replace(/^\s+|\s+$/g,"")};
_ASProxy.StrStartsWith=function(a,b){if(a.length==0||a.length<b.length)return false;return a.substr(0,b.length)==b};_ASProxy.StrEndsWith=function(a,b){if(a.length==0||a.length<b.length)return false;return a.substr(a.length-b.length)==b};_ASProxy.Enc={};
_ASProxy.Enc.EncodeElements=function(a,b,c,f,g,d,e,j){var k=0,h;for(k=0;k<a.length;k++){h=a[k];var l=h.attributes[b],n=h[b];l=l!=null?l.value:n;if(_ASProxy.IsEncodedByASProxy(l)==false){var o=false;if(g!=null&&d!=null){var m=h.attributes[g];m=m!=null?m.value:h[g];if(m!=null)if(m.toLowerCase()!=d.toLowerCase())continue}m=h.attributes.asproxydone;if(m==null||m.value!="1"&&m.value!="2")o=true;else if(m.value=="1"){m=h.attributes.encodedurl;if(m==null){_ASProxy.CallOriginalSetAttr(h,"encodedurl",l);c==
3&&e&&_ASProxy.CallOriginalSetAttr(h,e,j);o=true}else m=m.value;if(l!=m)if(l==window.location)continue;else o=true}if(o){o=_ASProxy.CorrectLocalUrlToOrginalCheck(l);n=_ASProxy.CorrectLocalUrlToOrginalCheck(n);_ASProxy.CallOriginalSetAttr(h,"asproxydone","1");_ASProxy.CallOriginalSetAttr(h,"originalurl",_ASProxy.GetBookmarkOnlyForCurrentPage(n));c==3&&e&&_ASProxy.CallOriginalSetAttr(h,e,j);if(f&&_userConfig.OrginalUrl){typeof ORG_IN_!="undefined"&&_ASProxy.AttachEvent(h,"mouseover",function(){ORG_IN_(this)});
typeof ORG_OUT_!="undefined"&&_ASProxy.AttachEvent(h,"mouseout",function(){ORG_OUT_()})}if(!(l==window.location&&o==l)){o=__UrlEncoder(o,c,true,null);_ASProxy.CallOriginalSetAttr(h,b,o);h[b]=o;_ASProxy.CallOriginalSetAttr(h,"encodedurl",o)}}}}};
_ASProxy.Enc.EncodeForms=function(){if(_userConfig.Forms==true){var a=0,b;for(a=0;a<document.forms.length;a++){b=document.forms.item(a);var c=b.attributes.action;c=c!=null?c.value:b.action;if(_ASProxy.IsEncodedByASProxy(c)==false){var f=false,g=b.attributes.asproxydone,d=b.method;if(g==null||g.value!="1"&&g.value!="2")f=true;else if(g.value=="1"){g=b.attributes.encodedurl;g=g==null?"":g.value;d=b.attributes.methodorginal;d=d==null?b.method:d.value;var e=g.indexOf("://",0);if(e==-1)g=document.location.protocol+
"//"+document.location.host+"/"+g;if(c!=g)f=true}if(f){_ASProxy.CallOriginalSetAttr(b,"asproxydone","1");_ASProxy.CallOriginalSetAttr(b,"methodorginal",d);c=__UrlEncoder(c,ENC_Page,false,"method="+d);_ASProxy.CallOriginalSetAttr(b,"action",c);_ASProxy.CallOriginalSetAttr(b,"encodedurl",c);b.method="POST"}}}window.setTimeout("_ASProxy.Enc.EncodeForms();",2E3)}};
_ASProxy.Enc.EncodeFrames=function(){if(_userConfig.Frames==true){var a=document.documentElement.getElementsByTagName("iframe");try{_ASProxy.Enc.EncodeElements(a,"src",3,false,null,null,"onload","_ASProxy.Enc.EncodeFrames()")}catch(b){_ASProxy.Log("Enc.EncodeFrames",b)}window.setTimeout("_ASProxy.Enc.EncodeFrames();",5E3)}};
_ASProxy.Enc.EncodeLinks=function(){if(_userConfig.Links==true){try{_ASProxy.Enc.EncodeElements(document.links,"href",0,true)}catch(a){_ASProxy.Log("Enc.EncodeLinks",a)}window.setTimeout("_ASProxy.Enc.EncodeLinks();",1E3)}};_ASProxy.Enc.EncodeImages=function(){if(_userConfig.Images==true){try{_ASProxy.Enc.EncodeElements(document.images,"src",1,true)}catch(a){_ASProxy.Log("Enc.EncodeImages",a)}window.setTimeout("_ASProxy.Enc.EncodeImages();",1E3)}};
_ASProxy.Enc.EncodeInputImages=function(){if(_userConfig.Images==true){var a=document.documentElement.getElementsByTagName("input");try{_ASProxy.Enc.EncodeElements(a,"src",1,true,"type","image")}catch(b){_ASProxy.Log("Enc.EncodeInputImages",b)}window.setTimeout("_ASProxy.Enc.EncodeInputImages();",4E3)}};
_ASProxy.Enc.EncodeScriptSources=function(){var a=document.documentElement.getElementsByTagName("script");try{_ASProxy.Enc.EncodeElements(a,"src",2,false)}catch(b){_ASProxy.Log("Enc.EncodeScriptSources",b)}window.setTimeout("_ASProxy.Enc.EncodeScriptSources();",4E3)};
_ASProxy.LocationObject=function(){this.search=_reqInfo.location.Search;this.href=_reqInfo.pageUrl;this.hash=window.location.hash!=null&&window.location.hash!=""?window.location.hash:_reqInfo.location.Hash;this.host=_reqInfo.location.Host;this.hostname=_reqInfo.location.Hostname;this.pathname=_reqInfo.location.Pathname;this.port=_reqInfo.location.Port;this.protocol=_reqInfo.location.Protocol;this.replace=window.LocationReplace;this.assign=window.LocationAssign;this.replace=_ASProxy.LocationReplace;
this.assign=_ASProxy.LocationAssign;this.reload=_ASProxy.LocationReload;this.URL=_reqInfo.pageUrl;this.toString=function(){return _reqInfo.pageUrl};this.toLocaleString=function(){return _reqInfo.pageUrl};this.length=this.href.length;this.anchor=this.href.anchor;this.big=this.href.big;this.blink=this.href.blink;this.bold=this.href.bold;this.charAt=this.href.charAt;this.charCodeAt=this.href.charCodeAt;this.fixed=this.href.fixed;this.fontcolor=this.href.fontcolor;this.fontsize=this.href.fontsize;this.fromCharCode=
this.href.fromCharCode;this.indexOf=this.href.indexOf;this.italics=this.href.italics;this.lastIndexOf=this.href.lastIndexOf;this.link=this.href.link;this.match=this.href.match;this.slice=this.href.slice;this.small=this.href.small;this.split=this.href.split;this.strike=this.href.strike;this.sub=this.href.sub;this.substr=this.href.substr;this.substring=this.href.substring;this.toLowerCase=this.href.toLowerCase;this.toUpperCase=this.href.toUpperCase};
function __CookieGet(a){return _ASProxy.GetDocumentCookie()}function __CookieSet(a){return _ASProxy.SetDocumentCookie(a)}_ASProxy.DocCookieString=document.cookie;_ASProxy.GetDocumentCookie=function(){_ASProxy.DocCookieString=document.cookie;for(var a="",b=0;b<_reqInfo.appliedCookiesList.length;b++){var c=_reqInfo.appliedCookiesList[b];c=_ASProxy.GetCookieByName(c);if(c!=null){c=_ASProxy.ParseASProxyCookie(c);if(c!=null&&c.length>0)a+=c}}return a};
_ASProxy.ParseASProxyCookie=function(a){var b="";a=a.split("&");for(var c=0;c<a.length;c++){var f=null,g=null,d=null,e=a[c];e=e.split(";");for(var j=0;j<e.length;j++){var k=e[j],h=k.indexOf("="),l=k.substr(0,h).replace("+","");l=_ASProxy.StrTrim(l);k=_ASProxy.StrTrim(k.substr(h+1,k.length-h-1));if(l=="Name")f=k;else if(l=="Value")g=k=unescape(k);else if(l=="Path")d=k}if(f!=null&&g!=null){f=f+"="+g;if(d==null||d=="")d="/";d=d.toLowerCase();g=_reqInfo.location.Pathname.toLowerCase();if(g.indexOf(d)==
0)b+=f+"; "}}return b};_ASProxy.SetDocumentCookie=function(a){if(!(a==null||a==""))return a=_ASProxy.ParseStandardCookieForSet(a)};
_ASProxy.ParseStandardCookieForSet=function(a){var b=null,c=null,f=null,g=null,d=null,e=null,j=false;a=a.split(";");for(var k=0;k<a.length;k++){var h=a[k],l=h.indexOf("="),n=h.substr(0,l).replace("+","");n=_ASProxy.StrTrim(n);h=_ASProxy.StrTrim(h.substr(l+1,h.length-l-1));if(k==0){b=n;c=h}else if(n=="expires")f=h;else if(n=="max-age")g=h;else if(n=="domain")d=h;else if(n=="path")e=h;else if(n=="secure")j=true}a="";if(b==null||c==null)return null;else{a="Name="+b;a+="; Value="+escape(c);if(f!=null)a+=
"; Expires="+f;if(g!=null)a+="; Max-Age="+g;if(d!=null)a+="; Domain="+d;if(e!=null)a+="; Path="+e;if(j)a+="; Secure=True"}b=_reqInfo.cookieName;c=c="";if(d!=null&&d!="")b=_ASProxy.GetASProxyCookieName(d);c=a;d=_ASProxy.GetCookieByName(b);if(d!=null&&d!="")c+="& "+d;c=escape(c);c=b+"="+c;if(f!=null)c+="; expires="+f;if(g!=null)c+="; max-age="+g;c+="; path=/";return c};
_ASProxy.GetCookieByName=function(a){a=a;for(var b=_ASProxy.DocCookieString.split(";"),c=0;c<b.length;c++){var f=b[c].split("="),g=_ASProxy.StrTrim(f[0]);if(a==g)return unescape(f[1])}return null};_ASProxy.GetASProxyCookieName=function(a){return a+_reqInfo.cookieNameExt};
_ASProxy.ParseHtml=function(a){if(typeof a!="string")return a;var b=/\.(src)\s*=\s*([^;}]+)/ig;a=a.replace(b,".$1=__UrlEncoder($2,ENC_Any)");b=/\.(action|location|href)\s*=\s*([^;}]+)/ig;a=a.replace(b,".$1=__UrlEncoder($2)");b=/\.innerHTML\s*(\+)?=\s*([^};]+)\s*/ig;a=a.replace(b,".innerHTML$1=_ASProxy.ParseHtml($2)");for(b=/\s(href|action)\s*=\s*(["']?)([^"'\s>]+)/ig;match=b.exec(a);)a=a.replace(match[0]," "+match[1]+"="+match[2]+__UrlEncoder(match[3]));for(b=/\s(src|background)\s*=\s*(["']?)([^"'\s>]+)/ig;match=
b.exec(a);)a=a.replace(match[0]," "+match[1]+"="+match[2]+__UrlEncoder(match[3],ENC_Any));for(b=/url\s*\(['"]?([^'"\)]+)['"]?\)/ig;match=b.exec(a);)a=a.replace(match[0],"url("+__UrlEncoder(match[1],ENC_Any)+")");for(b=/@import\s*['"]([^'"\(\)]+)['"]/ig;match=b.exec(a);)a=a.replace(match[0],'@import "'+__UrlEncoder(match[1],ENC_Any)+'"');return a};_ASProxy.ParseJs=function(){};
_ASProxy.CallOriginalSetAttr=function(a,b,c){if(a!=null)typeof a.OriginalSetAttribute=="undefined"?a.setAttribute(b,c):a.OriginalSetAttribute(b,c)};
_ASProxy.OverrideHtmlSetters=function(){if(typeof window.__defineSetter__!="undefined")try{var a=[HTMLTitleElement,HTMLTextAreaElement,HTMLTableSectionElement,HTMLTableRowElement,HTMLTableElement,HTMLTableColElement,HTMLTableCellElement,HTMLTableCaptionElement,HTMLStyleElement,HTMLSelectElement,HTMLScriptElement,HTMLParamElement,HTMLParagraphElement,HTMLOptionElement,HTMLOListElement,HTMLObjectElement,HTMLMetaElement,HTMLMapElement,HTMLMapElement,HTMLLinkElement,HTMLLIElement,HTMLLegendElement,HTMLLabelElement,
HTMLIsIndexElement,HTMLInputElement,HTMLImageElement,HTMLIFrameElement,HTMLHtmlElement,HTMLHRElement,HTMLHeadingElement,HTMLHeadElement,HTMLFrameSetElement,HTMLFrameElement,HTMLFormElement,HTMLFontElement,HTMLFieldSetElement,HTMLEmbedElement,HTMLDocument,HTMLDListElement,HTMLDivElement,HTMLButtonElement,HTMLBRElement,HTMLBodyElement,HTMLBaseFontElement,HTMLBaseElement,HTMLAreaElement,HTMLAnchorElement];try{a.push([HTMLElement,HTMLUListElement,HTMLQuoteElement,HTMLPreElement,HTMLModElement,HTMLMenuElement,
HTMLDirectoryElement,HTMLAppletElement])}catch(b){_ASProxy.Log("OverrideHtmlSetters interfaces.push",b)}var c=function(d,e,j){if(_ASProxy.IsEncodedByASProxy(e))return e;try{var k=d.toLowerCase();d=j;d=d==null?(this.tagName+"").toLowerCase():(d+"").toLowerCase();if(k=="src")e=d=="img"?__UrlEncoder(e,ENC_Images):d=="iframe"||d=="frame"?__UrlEncoder(e,ENC_Frames):__UrlEncoder(e,ENC_Any);else if(k=="href")e=d=="a"||d=="base"?__UrlEncoder(e):__UrlEncoder(e,ENC_Any);else if(k=="background")e=__UrlEncoder(e,
ENC_Images);else if(k=="action")e=d=="form"?e:__UrlEncoder(e,ENC_Any);else if(k=="innerHtml")e=_ASProxy.ParseHtml(e)}catch(h){_ASProxy.Log("_EncodeSetAttributeValue",h)}return e};_ASProxy.SetAttribute=function(d,e){try{if(d.toLowerCase()=="action"&&this.tagName.toLowerCase()=="form")_ASProxy.Setter_FormAction(this,e);else{e=c(d,e,this.tagName);this.OriginalSetAttribute(d,e)}}catch(j){_ASProxy.Log("_ASProxy.SetAttribute",j)}};_ASProxy.Setter_FormAction=function(d,e){var j=d.attributes.methodorginal;
j=j==null?j.value:d.method;d.OriginalSetAttribute("asproxydone","1");d.OriginalSetAttribute("methodorginal",j);e=_ASProxy.IsEncodedByASProxy(e)==false?__UrlEncoder(e,ENC_Page,false,"method="+j):e;d.OriginalSetAttribute("action",e);d.method="POST";d.OriginalSetAttribute("encodedurl",e)};_ASProxy.Setter_Src=function(d){this.OriginalSetAttribute("src",c("src",d,this.tagName))};_ASProxy.Setter_Href=function(d){this.OriginalSetAttribute("href",c("href",d,this.tagName))};_ASProxy.Setter_Background=function(d){this.OriginalSetAttribute("background",
c("background",d,this.tagName))};_ASProxy.Setter_InnerHtml=function(d){this.OriginalSetAttribute("innerHtml",c("innerHtml",d,this.tagName))};_ASProxy.Setter_Action=function(d){try{this.tagName.toLowerCase()=="form"?_ASProxy.Setter_FormAction(this,d):this.OriginalSetAttribute("action",c("action",d,this.tagName))}catch(e){_ASProxy.Log("Setter_Action",e)}};for(i=0;i<a.length;i++){var f=a[i].prototype;if(f!=null){f.OriginalSetAttribute=f.setAttribute;f.setAttribute=_ASProxy.SetAttribute;f.__defineSetter__("src",
_ASProxy.Setter_Src);f.__defineSetter__("action",_ASProxy.Setter_Action);f.__defineSetter__("href",_ASProxy.Setter_Href);f.__defineSetter__("background",_ASProxy.Setter_Background);f.__defineSetter__("innerHtml",_ASProxy.Setter_InnerHtml)}}}catch(g){_ASProxy.Log("OverrideHtmlSetters ALL",g)}};
_ASProxy.OverrideStandardsDeclare=function(){_ASProxy.WindowOpen=function(a,b,c,f){return _ASProxy.IsEncodedByASProxy(a)?window.OriginalOpen(a,b,c,f):window.OriginalOpen(__UrlEncoder(a),b,c,f)};_ASProxy.LocationAssign=function(a){_ASProxy.IsEncodedByASProxy(a)||(a=__UrlEncoder(a));return window.location.href=a};_ASProxy.LocationReplace=function(a){a=_ASProxy.IsEncodedByASProxy(a)?a:__UrlEncoder(a);return window.location.replace==_ASProxy.LocationReplace?window.LocationReplace(a):window.location.replace(a)};
_ASProxy.LocationReload=function(){return window.location.reload==_ASProxy.LocationReload?window.LocationReload():window.location.reload()};_ASProxy.DocumentWrite=function(a){a=a;if(_ASProxy.ParseHtml){a=_ASProxy.ParseHtml(a);return document.OriginalWrite(a)}};_ASProxy.DocumentWriteLn=function(a){a=a;if(_ASProxy.ParseHtml){a=_ASProxy.ParseHtml(a);return document.OriginalWriteLn(a)}}};
_ASProxy.OverrideStandards=function(){try{document.XDomain=_WindowLocation.host}catch(a){_ASProxy.Log("document.XDOMAIN failed",a)}try{window.open=_ASProxy.WindowOpen}catch(b){_ASProxy.Log("OVR window.open failed",b)}try{document.open=_ASProxy.WindowOpen}catch(c){_ASProxy.Log("OVR document.open failed",c)}try{open=_ASProxy.WindowOpen}catch(f){_ASProxy.Log("OVR open failed",f)}try{window.location.replace=_ASProxy.LocationReplace}catch(g){_ASProxy.Log("OVR window.location failed",g)}try{location.replace=
_ASProxy.LocationReplace}catch(d){_ASProxy.Log("OVR location.replace failed",d)}try{document.write=_ASProxy.DocumentWrite}catch(e){_ASProxy.Log("OVR document.write failed",e)}try{document.writeln=_ASProxy.DocumentWriteLn}catch(j){_ASProxy.Log("OVR document.writeln failed",j)}};
_ASProxy.StartupDynamicEncoders=function(){window.setTimeout("_ASProxy.Enc.EncodeLinks();",500);window.setTimeout("_ASProxy.Enc.EncodeImages();",700);window.setTimeout("_ASProxy.Enc.EncodeInputImages();",2E3);window.setTimeout("_ASProxy.Enc.EncodeForms();",1E3);window.setTimeout("_ASProxy.Enc.EncodeFrames();",2E3);window.setTimeout("_ASProxy.Enc.EncodeScriptSources();",4E3)};
_ASProxy.Initialize=function(){_ASProxy.OverrideStandardsDeclare();_WindowLocation=new _ASProxy.LocationObject;_ASProxy.ReqLocation=_WindowLocation;_ASProxy.OverrideStandards();_ASProxy.OverrideHtmlSetters();_ASProxy.StartupDynamicEncoders()};_ASProxy.Initialize();